### ISSUE TITLE
Dashactyl Fork. Illegal activity.

### ISSUE THREAD

**Issue by MattReal6833** [Qwakeactyl/Qwakeactyl#2]
Hello There
I'm Matt from Votion Development (The real developers of Dashactyl)
We've noticed that you've forked Dashactyl v0.4 and claimed it to be your own. This is illegal and will result in legal actions. 
Proof: 
![image](https://user-images.githubusercontent.com/56598575/153255941-342429db-2e70-490d-b590-9ee58b072392.png)
![image](https://user-images.githubusercontent.com/56598575/153255969-99f5aea2-d0b0-44bb-b2a5-16439c934710.png)

Feel free to check for yourself: https://github.com/Qwakeactyl/Qwakeactyl/search?q=dashactyl

Unable to take this down will result in a DMCA. 
If you have any questions, feel free to join our server: https://discord.gg/ERd2psC5kp

**Comment by MattReal6833** [comment]
You have one day.

**Comment by Nightmaregodss** [comment]
sorry for that but we fixed that all stuff in our ide but our developer already released Qwakeactyl and we were not able to commit it bcz of git issue but we fixed it now.

**Comment by MattReal6833** [comment]
> sorry for that but we fixed that all stuff in our ide but our developer already released Qwakeactyl and we were not able to commit it bcz of git issue but we fixed it now.

This isn't a code "issue". This is legal stuff

**Comment by Nightmaregodss** [comment]
but they are a lot dashactyl forks

**Comment by MattReal6833** [comment]
> but they are a lot dashactyl forks

Those still have the credits in them. Yours do not.

**Comment by Nightmaregodss** [comment]
https://github.com/Reliactyl/Reliactyl

**Comment by MattReal6833** [comment]
> https://github.com/Reliactyl/Reliactyl

We're going there next. One by one, we're going to take them down.

**Comment by Nightmaregodss** [comment]
we have given you credits

**Comment by MattReal6833** [comment]
> we have given you credits

Care to show me where?

**Comment by Nightmaregodss** [comment]
check about me readme

**Comment by MattReal6833** [comment]
Let me discuss with the owners. I'll get back to you soon

**Comment by Nightmaregodss** [comment]
they are a lot dash like heliactyl and etc

**Comment by Nightmaregodss** [comment]
we have given you credits always

**Comment by asish-op** [comment]
we have given credits
