### ISSUE TITLE
please help me i am getting error

### ISSUE THREAD

**Issue by YESWAGGAMING** [Qwakeactyl/Qwakeactyl#5]
![image](https://user-images.githubusercontent.com/83405580/165333740-2fb7e0bd-1555-4c75-a92b-98dc4dee7478.png)
![image](https://user-images.githubusercontent.com/83405580/165333748-e07ef2f8-6ef5-431c-a2b3-3deedf99329a.png)
![image](https://user-images.githubusercontent.com/83405580/165333757-565474d0-2bf1-4c49-acd1-b7713eb1fc02.png)

**Comment by IndianDevInc** [comment]
discord dm ashish or kns

**Comment by JJProplay** [comment]
I have the same problem, I am trying to run it on Ubuntu 20.04 LTS. 
Can you please direct me to your support server or something?

thx a lot 🙂

**Comment by JJProplay** [comment]
> ashish
